# Generated by Django 5.2.10 on 2026-02-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_boissons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boissons',
            options={'verbose_name': 'Boisson', 'verbose_name_plural': 'Boissons'},
        ),
        migrations.AlterModelTable(
            name='boissons',
            table='menu_boissons',
        ),
    ]
