# Generated by Django 5.2.10 on 2026-02-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_boissons_options_alter_boissons_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzas',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='tacos',
            options={'verbose_name': 'Tacos', 'verbose_name_plural': 'Tacos'},
        ),
        migrations.RenameField(
            model_name='pizzas',
            old_name='ingredients_pizzas',
            new_name='ingredients_pizza',
        ),
        migrations.RenameField(
            model_name='tacos',
            old_name='ingredients_tacos',
            new_name='ingredients_taco',
        ),
        migrations.AlterModelTable(
            name='pizzas',
            table='menu_pizzas',
        ),
        migrations.AlterModelTable(
            name='tacos',
            table='menu_tacos',
        ),
    ]
