# Generated by Django 5.2.10 on 2026-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_pizzas_options_alter_tacos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
    ]
