# Generated by Django 5.2.10 on 2026-02-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingredient_pizza_pizzas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient_pizza',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pizzas',
            options={},
        ),
        migrations.RenameField(
            model_name='tacos',
            old_name='ingredients',
            new_name='ingredients_tacos',
        ),
    ]
