# Generated by Django 5.2.10 on 2026-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_ingredient_pizza_options_alter_pizzas_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Ingredient_tacos',
        ),
    ]
