# Generated by Django 5.2.10 on 2026-02-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_ingredient_ingredient_tacos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boissons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='boisson_image/')),
                ('price', models.FloatField(default=10)),
            ],
        ),
    ]
