# Generated by Django 5.2.10 on 2026-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='boissons',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pizzas',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tacos',
            name='image',
        ),
        migrations.AddField(
            model_name='boissons',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacos',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
